export const BRAZILIAN_STATES = [
  { state: "Acre", uf: "AC", cities: ["Rio Branco", "Cruzeiro do Sul", "Sena Madureira"] },
  { state: "Alagoas", uf: "AL", cities: ["Maceió", "Arapiraca", "Rio Largo", "Palmeira dos Índios"] },
  { state: "Amapá", uf: "AP", cities: ["Macapá", "Santana", "Laranjal do Jari"] },
  { state: "Amazonas", uf: "AM", cities: ["Manaus", "Parintins", "Itacoatiara", "Manacapuru"] },
  { state: "Bahia", uf: "BA", cities: ["Salvador", "Feira de Santana", "Vitória da Conquista", "Camaçari", "Ilhéus", "Itabuna", "Lauro de Freitas", "Juazeiro", "Barreiras"] },
  { state: "Ceará", uf: "CE", cities: ["Fortaleza", "Caucaia", "Juazeiro do Norte", "Maracanaú", "Sobral", "Crato"] },
  { state: "Distrito Federal", uf: "DF", cities: ["Brasília"] },
  { state: "Espírito Santo", uf: "ES", cities: ["Vitória", "Vila Velha", "Serra", "Cariacica", "Cachoeiro de Itapemirim", "Linhares"] },
  { state: "Goiás", uf: "GO", cities: ["Goiânia", "Aparecida de Goiânia", "Anápolis", "Rio Verde", "Luziânia", "Águas Lindas de Goiás"] },
  { state: "Maranhão", uf: "MA", cities: ["São Luís", "Imperatriz", "Timon", "Caxias", "Codó"] },
  { state: "Mato Grosso", uf: "MT", cities: ["Cuiabá", "Várzea Grande", "Rondonópolis", "Sinop", "Tangará da Serra"] },
  { state: "Mato Grosso do Sul", uf: "MS", cities: ["Campo Grande", "Dourados", "Três Lagoas", "Corumbá", "Ponta Porã"] },
  { state: "Minas Gerais", uf: "MG", cities: ["Belo Horizonte", "Uberlândia", "Contagem", "Juiz de Fora", "Betim", "Montes Claros", "Ribeirão das Neves", "Uberaba", "Governador Valadares", "Ipatinga", "Poços de Caldas"] },
  { state: "Pará", uf: "PA", cities: ["Belém", "Ananindeua", "Santarém", "Marabá", "Castanhal", "Parauapebas"] },
  { state: "Paraíba", uf: "PB", cities: ["João Pessoa", "Campina Grande", "Santa Rita", "Patos", "Bayeux"] },
  { state: "Paraná", uf: "PR", cities: ["Curitiba", "Londrina", "Maringá", "Ponta Grossa", "Cascavel", "São José dos Pinhais", "Foz do Iguaçu", "Colombo"] },
  { state: "Pernambuco", uf: "PE", cities: ["Recife", "Jaboatão dos Guararapes", "Olinda", "Caruaru", "Petrolina", "Paulista", "Cabo de Santo Agostinho"] },
  { state: "Piauí", uf: "PI", cities: ["Teresina", "Parnaíba", "Picos", "Piripiri", "Floriano"] },
  { state: "Rio de Janeiro", uf: "RJ", cities: ["Rio de Janeiro", "São Gonçalo", "Duque de Caxias", "Nova Iguaçu", "Niterói", "Belford Roxo", "Campos dos Goytacazes", "São João de Meriti", "Petrópolis", "Volta Redonda", "Magé", "Macaé"] },
  { state: "Rio Grande do Norte", uf: "RN", cities: ["Natal", "Mossoró", "Parnamirim", "São Gonçalo do Amarante", "Caicó"] },
  { state: "Rio Grande do Sul", uf: "RS", cities: ["Porto Alegre", "Caxias do Sul", "Pelotas", "Canoas", "Santa Maria", "Gravataí", "Viamão", "Novo Hamburgo", "São Leopoldo", "Passo Fundo"] },
  { state: "Rondônia", uf: "RO", cities: ["Porto Velho", "Ji-Paraná", "Ariquemes", "Vilhena", "Cacoal"] },
  { state: "Roraima", uf: "RR", cities: ["Boa Vista", "Rorainópolis", "Caracaraí"] },
  { state: "Santa Catarina", uf: "SC", cities: ["Florianópolis", "Joinville", "Blumenau", "São José", "Chapecó", "Criciúma", "Itajaí", "Balneário Camboriú", "Lages"] },
  { state: "São Paulo", uf: "SP", cities: ["São Paulo", "Guarulhos", "Campinas", "São Bernardo do Campo", "Santo André", "Osasco", "São José dos Campos", "Ribeirão Preto", "Sorocaba", "Santos", "São José do Rio Preto", "Mogi das Cruzes", "Diadema", "Jundiaí", "Piracicaba", "Bauru", "Carapicuíba", "Mauá", "Itaquaquecetuba", "São Vicente", "Franca", "Praia Grande", "Guarujá", "Taubaté", "Limeira", "Suzano", "Taboão da Serra", "Sumaré", "Barueri", "Marília"] },
  { state: "Sergipe", uf: "SE", cities: ["Aracaju", "Nossa Senhora do Socorro", "Lagarto", "Itabaiana"] },
  { state: "Tocantins", uf: "TO", cities: ["Palmas", "Araguaína", "Gurupi", "Porto Nacional"] },
];
